name: geospatial
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - attrs=23.1.0=py312h06a4308_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py312ha883a20_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.7.4=py312h06a4308_0
  - cfitsio=3.470=h5893167_7
  - click=8.1.7=py312h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - fiona=1.9.5=py312h526ad5a_0
  - flask=2.2.2=py312h06a4308_0
  - flask_cors=4.0.0=pyhd8ed1ab_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - gdal=3.6.2=py312h51fade5_4
  - geopandas=0.9.0=pyhd8ed1ab_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=h2a26cda_3
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - itsdangerous=2.2.0=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json-c=0.16=h5eee18b_0
  - kealib=1.5.0=hd940352_1
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal=3.6.2=heb138ec_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libkml=1.3.0=h096b73e_7
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=5.1.0=h01e95a1_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hfdd30dd_2
  - libzip=1.8.0=h6ac8c49_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - minizip=4.0.3=hf59b114_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.14=h5eee18b_0
  - pandas=2.2.2=py312h526ad5a_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.0=py312h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - proj=9.3.1=he5811b7_0
  - pyproj=3.6.1=py312h6268720_0
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312h06a4308_0
  - qhull=2020.2=hdb19cb5_2
  - readline=8.2=h5eee18b_0
  - rtree=1.0.1=py312h06a4308_0
  - setuptools=69.5.1=py312h06a4308_0
  - shapely=2.0.1=py312h1789038_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tiledb=2.3.3=h77177df_3
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - uriparser=0.9.7=h5eee18b_0
  - werkzeug=2.2.3=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xerces-c=3.2.4=h6a678d5_1
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
prefix: /home/liberrisford/miniconda3/envs/geospatial
